name:
  - mdl-modules
channels:
  - defaults
dependencies:
  - blas                      1.0                         mkl
  - bottleneck                1.4.2           py312h4b0e54e_0
  - brotli                    1.0.9                h2bbff1b_8
  - brotli-bin                1.0.9                h2bbff1b_8
  - brotli-python             1.0.9           py312hd77b12b_8
  - bzip2                     1.0.8                h2bbff1b_6
  - ca-certificates           2024.11.26           haa95532_0
  - cairo                     1.18.0               h1fef639_0    conda-forge
  - certifi                   2024.8.30       py312haa95532_0
  - chardet                   4.0.0           py312haa95532_1003
  - charset-normalizer        3.3.2              pyhd3eb1b0_0
  - contourpy                 1.3.1           py312h214f63a_0
  - cycler                    0.11.0             pyhd3eb1b0_0
  - expat                     2.6.3                h5da7b33_0
  - filelock                  3.13.1          py312haa95532_0
  - font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0
  - font-ttf-inconsolata      2.001                hcb22688_0
  - font-ttf-source-code-pro  2.030                hd3eb1b0_0
  - font-ttf-ubuntu           0.83                 h8b1ccd4_0
  - fontconfig                2.14.2               hbde0cde_0    conda-forge
  - fonts-anaconda            1                    h8fa9717_0
  - fonts-conda-ecosystem     1                    hd3eb1b0_0
  - fonttools                 4.51.0          py312h2bbff1b_0
  - freetype                  2.12.1               ha860e81_0
  - freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
  - giflib                    5.2.2                h7edc060_0
  - greenlet                  3.0.1           py312hd77b12b_0
  - icc_rt                    2022.1.0             h6049295_2
  - icu                       73.2                 h63175ca_0    conda-forge
  - idna                      3.7             py312haa95532_0
  - intel-openmp              2023.1.0         h59b6b97_46320
  - jinja2                    3.1.4           py312haa95532_1
  - jpeg                      9e                   h827c3e9_3
  - kiwisolver                1.4.4           py312hd77b12b_0
  - krb5                      1.21.3               hdf4eb48_0    conda-forge
  - lcms2                     2.12                 h83e58a3_0
  - lerc                      3.0                  hd77b12b_0
  - libboost                  1.84.0               h9a677ad_3    conda-forge
  - libboost-python           1.84.0          py312hbaa7e33_6    conda-forge
  - libbrotlicommon           1.0.9                h2bbff1b_8
  - libbrotlidec              1.0.9                h2bbff1b_8
  - libbrotlienc              1.0.9                h2bbff1b_8
  - libdeflate                1.17                 h2bbff1b_1
  - libexpat                  2.6.3                he0c23c2_0    conda-forge
  - libffi                    3.4.4                hd77b12b_1
  - libglib                   2.78.4               ha17d25a_0
  - libiconv                  1.17                 hcfcfb64_2    conda-forge
  - libjpeg-turbo             2.0.0                h196d8e1_0
  - libpng                    1.6.39               h8cc25b3_0
  - libpq                     16.6                 hab9416b_0    conda-forge
  - librdkit                  2024.03.6            h4c5bbc8_0    conda-forge
  - libsqlite                 3.47.0               h2466b09_1    conda-forge
  - libtiff                   4.5.1                hd77b12b_0
  - libuv                     1.48.0               h827c3e9_0
  - libwebp                   1.3.2                hbc33d0d_0
  - libwebp-base              1.3.2                h3d04722_1
  - libzlib                   1.2.13               h2466b09_6    conda-forge
  - lz4-c                     1.9.4                h2bbff1b_1
  - markupsafe                2.1.3           py312h2bbff1b_0
  - matplotlib-base           3.9.2           py312he19b0ae_1
  - mkl                       2023.1.0         h6b88ed4_46358
  - mkl-service               2.4.0           py312h2bbff1b_1
  - mkl_fft                   1.3.11          py312h827c3e9_0
  - mkl_random                1.2.8           py312h0158946_0
  - mpmath                    1.3.0           py312haa95532_0
  - networkx                  3.2.1           py312haa95532_0
  - numexpr                   2.10.1          py312h4cd664f_0
  - numpy                     2.0.1           py312hfd52020_1
  - numpy-base                2.0.1           py312h4dde369_1
  - openjpeg                  2.5.2                hae555c5_0
  - openssl                   3.4.0                h2466b09_0    conda-forge
  - packaging                 24.1            py312haa95532_0
  - pandas                    2.2.3           py312h5da7b33_0
  - pcre2                     10.42                h0ff8eda_1
  - pillow                    11.0.0          py312hb5480e2_0
  - pip                       24.2            py312haa95532_0
  - pixman                    0.43.4               h63175ca_0    conda-forge
  - pycairo                   1.27.0          py312h487989a_0    conda-forge
  - pyparsing                 3.2.0           py312haa95532_0
  - pysocks                   1.7.1           py312haa95532_0
  - python                    3.12.3          h2628c8c_0_cpython    conda-forge
  - python-dateutil           2.9.0post0      py312haa95532_2
  - python-tzdata             2023.3             pyhd3eb1b0_0
  - python_abi                3.12                    5_cp312    conda-forge
  - pytz                      2024.1          py312haa95532_0
  - pyyaml                    6.0.2           py312h827c3e9_0
  - rdkit                     2024.03.6       py312h9d9823f_0    conda-forge
  - reportlab                 4.2.5           py312h4389bb4_0    conda-forge
  - requests                  2.32.3          py312haa95532_1
  - rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
  - scipy                     1.14.1          py312h9d85e7c_0
  - setuptools                75.1.0          py312haa95532_0
  - six                       1.16.0             pyhd3eb1b0_1
  - sqlalchemy                2.0.34          py312h54f65d0_0
  - sqlite                    3.45.3               h2bbff1b_0
  - sympy                     1.13.2          py312haa95532_0
  - tbb                       2021.8.0             h59b6b97_0
  - tk                        8.6.14               h0416ee5_0
  - typing-extensions         4.11.0          py312haa95532_0
  - typing_extensions         4.11.0          py312haa95532_0
  - tzdata                    2024b                h04d1e81_0
  - ucrt                      10.0.20348.0         haa95532_0
  - unicodedata2              15.1.0          py312h2bbff1b_0
  - urllib3                   2.2.3           py312haa95532_0
  - vc                        14.40                h2eaa2aa_1
  - vc14_runtime              14.42.34433         he29a5d6_23    conda-forge
  - vs2015_runtime            14.42.34433         hdffcdeb_23    conda-forge
  - wheel                     0.44.0          py312haa95532_0
  - win_inet_pton             1.1.0           py312haa95532_0
  - xz                        5.4.6                h8cc25b3_1
  - yaml                      0.2.5                he774522_0
  - zlib                      1.2.13               h2466b09_6    conda-forge
  - zstd                      1.5.6                h8880b57_0
