package:
  name: my_project
  version: 0.1.0

source:
  path: .

build:
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas

about:
  home: https://github.com/yourusername/my_project
  license: MIT
  summary: A sample Python project
